name: FOSS Build

on:
  push:
    branches:
    - '*-FOSS'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Build with Gradle
      run: ./gradlew assemblePlayFossProdRelease

    - name: Sign APKs
      env:
        # If you want to generate a keystore secret, run these commands:
        # keytool -genkey -v -keystore apksign.keystore -alias apksign -keyalg RSA -keysize 4096
        # cat apksign.keystore | base64
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
      run: |
        echo "${KEYSTORE_BASE64}" | base64 -d > apksign.keystore
        for apk in app/build/outputs/apk/playFossProd/release/*-unsigned-*.apk; do
        out=${apk/-unsigned-/-signed-}
        ${ANDROID_HOME}/build-tools/30.0.2/apksigner sign --ks apksign.keystore --ks-pass env:KEYSTORE_PASS --out "${out}" "${apk}"
        echo "$(sha256sum ${out}) $(basename ${out})"
        done
        rm apksign.keystore

    - uses: actions/upload-artifact@v2
      with:
        name: Release APK
        path: app/build/outputs/apk/playFossProd/release/*universal*signed*.apk
